### ISSUE TITLE
Installation and running

### ISSUE THREAD

**Issue by tenguzame** [abremges/CAMITAX#18]
Dear Andreas,
I'm trying to install your package, but it keeps throwing errors at me. Maybe there's something I got wrong in your installation procedures.
First, I activated docker on my terminal and cloned this repository in my home.
Then, I entered the new repository directory and installed nextflow using the command provided at their homepage ("curl -s https://get.nextflow.io | bash ").
But when I enter your pull command, the program throws this error at me:

`N E X T F L O W  ~  version 19.01.0
ERROR ~ Project config file is malformed -- Cause: No signature of method: nextflow.config.ConfigParser$_parse_closure5.memory() is applicable for argument types: (String) values: [16 GB]
Possible solutions: every(), every(), every(groovy.lang.Closure), every(groovy.lang.Closure), getAt(java.lang.String), getAt(java.lang.String)
`

I went to check for some typos in the nextflow.config file, and found that the program doesn't seem to like these lines: 
`memory '24 GB'`
I tried to fix the typo by inserting all the required "="s and removed the ''s, but then, as I re-run the program, it throws the following error:
`ERROR ~ Project config file is malformed -- Cause: No signature of method: java.lang.Integer.call() is applicable for argument types: (ConfigObject) values: [[:]]`
What am I doing wrong? How should I install CAMITAX?
Best regards

**Comment by abremges** [comment]
My mistake (and bad practice, sorry), should be fixed with https://github.com/CAMI-challenge/CAMITAX/commit/3ed20c16e0bce48791d26929ad311f1ce16ff1d6

I forgot to push the local config file after I committed a broken version to main. 👎 
We are currently testing a new release candidate, should be online in 1-2 days... 
So either give it another try or wait for the tested version. Sorry again & thank you!

**Comment by tenguzame** [comment]
Dear Andreas,
Thanks for the quick reply. I fixed the config file as you showed, but now nextflow complains it cannot pull anything because there are uncommitted changes. I guess I'll wait for your new release.

**Comment by abremges** [comment]
Possibly a side effect from cloning the repository first (which you don't need). Delete the cloned repository, then run `nextflow drop CAMI-challenge/CAMITAX` and `nextflow pull CAMI-challenge/CAMITAX`

But might be a good idea to wait a couple of days, the new release will also come with updated reference data = better results. I'll ask @AlphaSquad to also test it extensively in case I mess up things again. ;)

**Comment by tenguzame** [comment]
Well, then, I'll give it an immediate try to see if everything goes well, then I'll be using the updated version for the real thing. Thanks for your efforts!

**Comment by abremges** [comment]
Great, let me know if and how things work out! Notice that installation will take a while because 40 GB of reference data need to be downloaded first...

**Comment by tenguzame** [comment]
Managed to pull it yesterday evening! However, it throws me the following error, which prevents me from running it:
`WARN: There's no process matching config selector: centrifuge`
I checked everything but I can't see any error!

**Comment by abremges** [comment]
This is just a warning, no error, because there is no process `centrifuge` in `init.nf` (the database download). I'll try to find a better way but it should still run.

**Comment by abremges** [comment]
While the ugly warning is still in place, I just updated CAMITAX and confirmed that everything is working (for me). Please answer here or open a new issue if you run into trouble. Thanks!
